### PR TITLE
Implements $elemMatch query operator. Due to rs/rest-layer #237.

### PR DESCRIPTION
**Pull request by Dragomir-Ivanov**

### CODE REVIEW

**Comment by smyrman** [comment]
@Dragomir-Ivanov, is this still needed? Want to get the CI passing?

**Comment by Dragomir-Ivanov** [comment]
@smyrman It seems that it failed because it needed some parts of `rest-layer` not yet merged. They are merged now. Is there any way to restart the CI as it is?

**Comment by smyrman** [comment]
It will download the rest-layer version from `go.mod` (just updated to v0.2.0); so probably best if you fetch & rebase on master, then repush.

**Comment by Dragomir-Ivanov** [comment]
Done

**Pull request merged**
